### PR TITLE
Feature getServices

### PR DESCRIPTION
**Pull request by JoelLarson**
This pull request is in reference to: https://github.com/reswitched/pegaswitch/issues/37

It adds a basic helper function to use for grouping together multiple services in one call. The issue above notes the design considerations.

- [x] Implement getServices function.
- [x] Find all places where multiple services are called and replace with new syntax.
- [ ] Add test files for inputs/outputs.
- [x] Test this system with a real Switch.

### CODE REVIEW

**Comment by misson20000** [comment]
I can't test against a real console right now, but if it works, looks good to me

**Comment by Jhynjhiruu** [comment]
Has no-one tested with a real console yet? If not, I just got it to work so I can.

**Comment by misson20000** [comment]
I have already tested and merged.

**Comment by Jhynjhiruu** [comment]
Oh OK never mind then

**Pull request merged**
